"""核心算法模块.

包含分箱、编码、特征筛选、指标计算、可视化、金融计算、特征工程等核心功能。
"""

# 分箱模块
from .binning import (
    BaseBinning,
    UniformBinning,
    QuantileBinning,
    TreeBinning,
    CartBinning,
    ChiMergeBinning,
    BestKSBinning,
    BestIVBinning,
    OptimalBinning,
    MDLPBinning,
    ORBinning,
    CustomObjectives,
    KMeansBinning,
    MonotonicBinning,
    GeneticBinning,
    SmoothBinning,
    KernelDensityBinning,
    BestLiftBinning,
    TargetBadRateBinning,
)

# 指标计算模块
from .metrics import (
    ks, auc, gini,
    accuracy, precision, recall, f1,
    ks_bucket, roc_curve,
    confusion_matrix, classification_report,
    psi, csi,
    psi_table, csi_table,
    iv, iv_table,
    feature_importance,
    mse, mae, rmse, r2,
)

# 编码器模块
from .encoders import (
    BaseEncoder,
    WOEEncoder,
    TargetEncoder,
    CountEncoder,
    OneHotEncoder,
    OrdinalEncoder,
    QuantileEncoder,
    CatBoostEncoder,
)

# 特征筛选模块
from .selectors import (
    BaseFeatureSelector,
    SelectionReportCollector,
    VarianceSelector,
    NullSelector,
    ModeSelector,
    CorrSelector,
    VIFSelector,
    IVSelector,
    LiftSelector,
    PSISelector,
    CardinalitySelector,
    TypeSelector,
    RegexSelector,
    FeatureImportanceSelector,
    NullImportanceSelector,
    RFESelector,
    SequentialFeatureSelector,
    StepwiseSelector,
    BorutaSelector,
    MutualInfoSelector,
    Chi2Selector,
    FTestSelector,
    CompositeFeatureSelector,
    ScorecardFeatureSelection,
)

# 模型模块
from .models import (
    BaseLoss,
    BaseMetric,
    FocalLoss,
    AsymmetricFocalLoss,
    BalancedFocalLoss,
    WeightedBCELoss,
    CostSensitiveLoss,
    BadDebtLoss,
    ApprovalRateLoss,
    ProfitMaxLoss,
    OrdinalRankLoss,
    LiftFocusedLoss,
    RankingAUCProxyLoss,
    KSFocusedLoss,
    TopKBadCaptureLoss,
    AmountWeightedLoss,
    ExpectedValueLoss,
    KSMetric,
    GiniMetric,
    PSIMetric,
    XGBoostLossAdapter,
    LightGBMLossAdapter,
    CatBoostLossAdapter,
    TabNetLossAdapter,
    NGBoostLossAdapter,
)

# 可视化模块
from .viz import *

# 金融计算模块
from .financial import (
    fv,
    pv,
    pmt,
    nper,
    ipmt,
    ppmt,
    rate,
    npv,
    irr,
    mirr,
)

# 特征工程模块
from .feature_engineering import NumExprDerive

# 规则引擎模块
from .rules import (
    Rule,
    get_columns_from_query,
    optimize_expr,
    beautify_expr,
    get_expr_variables,
)

__all__ = [
    # 分箱
    'BaseBinning',
    'UniformBinning',
    'QuantileBinning',
    'TreeBinning',
    'CartBinning',
    'ChiMergeBinning',
    'BestKSBinning',
    'BestIVBinning',
    'OptimalBinning',
    'MDLPBinning',
    'ORBinning',
    'CustomObjectives',
    'KMeansBinning',
    'MonotonicBinning',
    'GeneticBinning',
    'SmoothBinning',
    'KernelDensityBinning',
    'BestLiftBinning',
    'TargetBadRateBinning',

    'ks', 'auc', 'gini',
    'accuracy', 'precision', 'recall', 'f1',
    'ks_bucket', 'roc_curve',
    'confusion_matrix', 'classification_report',
    'psi', 'csi',
    'psi_table', 'csi_table',
    'iv', 'iv_table',
    'feature_importance',
    'mse', 'mae', 'rmse', 'r2',

    # 编码器
    'BaseEncoder',
    'WOEEncoder',
    'TargetEncoder',
    'CountEncoder',
    'OneHotEncoder',
    'OrdinalEncoder',
    'QuantileEncoder',
    'CatBoostEncoder',

    # 特征筛选
    'BaseFeatureSelector',
    'SelectionReportCollector',
    'VarianceSelector',
    'NullSelector',
    'ModeSelector',
    'CorrSelector',
    'VIFSelector',
    'IVSelector',
    'LiftSelector',
    'PSISelector',
    'CardinalitySelector',
    'TypeSelector',
    'RegexSelector',
    'FeatureImportanceSelector',
    'NullImportanceSelector',
    'RFESelector',
    'SequentialFeatureSelector',
    'StepwiseSelector',
    'BorutaSelector',
    'MutualInfoSelector',
    'Chi2Selector',
    'FTestSelector',
    'CompositeFeatureSelector',
    'ScorecardFeatureSelection',

    # 模型/损失函数
    'BaseLoss',
    'BaseMetric',
    'FocalLoss',
    'AsymmetricFocalLoss',
    'BalancedFocalLoss',
    'WeightedBCELoss',
    'CostSensitiveLoss',
    'BadDebtLoss',
    'ApprovalRateLoss',
    'ProfitMaxLoss',
    'OrdinalRankLoss',
    'LiftFocusedLoss',
    'RankingAUCProxyLoss',
    'KSFocusedLoss',
    'TopKBadCaptureLoss',
    'AmountWeightedLoss',
    'ExpectedValueLoss',
    'KSMetric',
    'GiniMetric',
    'PSIMetric',
    'XGBoostLossAdapter',
    'LightGBMLossAdapter',
    'CatBoostLossAdapter',
    'TabNetLossAdapter',
    'NGBoostLossAdapter',

    # 可视化
    'bin_plot',
    'corr_plot',
    'ks_plot',
    'hist_plot',
    'psi_plot',
    'dataframe_plot',
    'distribution_plot',
    'bin_trend_plot',
    'batch_bin_trend_plot',
    'bin_overdues_plot',
    'plot_weights',
    'roc_plot',
    'pr_plot',
    'lift_plot',
    'gain_plot',
    'confusion_matrix_plot',
    'calibration_plot',
    'score_dist_plot',
    'score_bin_plot',
    'threshold_analysis_plot',
    'strategy_compare_plot',
    'vintage_plot',
    'feature_importance_plot',
    'approval_rate_trend_plot',
    'bad_rate_trend_plot',
    'variable_iv_plot',
    'variable_woe_trend_plot',
    'variable_psi_heatmap',
    'variable_importance_grouped_plot',
    'variable_missing_badrate_plot',
    'score_ks_plot',
    'score_distribution_comparison_plot',
    'score_badrate_bin_plot',
    'score_lift_plot',
    'score_approval_badrate_curve',
    'feature_trend_by_time',
    'feature_drift_comparison',
    'feature_effectiveness_by_segment',
    'feature_cross_heatmap',
    'population_drift_monitor',
    'segment_scorecard_comparison',
    'setup_axis_style',
    'save_figure',
    'get_or_create_ax',
    'create_legend',
    'format_bin_label',
    'DEFAULT_COLORS',
    'set_style',
    'reset_style',
    'get_current_theme',
    'get_palette',
    'get_font_sizes',
    'get_defaults',
    'PRIMARY_COLORS',
    'EXTENDED_COLORS',
    'SEMANTIC_COLORS',
    'GRADIENT_PALETTES',

    # 金融计算
    'fv',
    'pv',
    'pmt',
    'nper',
    'ipmt',
    'ppmt',
    'rate',
    'npv',
    'irr',
    'mirr',

    # 特征工程
    'NumExprDerive',

    # 规则引擎
    'Rule',
    'get_columns_from_query',
    'optimize_expr',
    'beautify_expr',
    'get_expr_variables',
]
